// apps/server/templates/vue-vite/src/App.vue
<script setup>
import { ref } from "vue";

const count = ref(0);
</script>

<template>
  <main>
    <h1>Hello from your Vue playground</h1>
    <p>Edit <code>src/App.vue</code> and save — the page updates itself.</p>
    <button @click="count++">Clicked {{ count }} times</button>
  </main>
</template>

// apps/server/templates/react-vite/src/App.jsx
import { useState } from "react";

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <main>
      <h1>Hello from your playground</h1>
      <p>Edit <code>src/App.jsx</code> and save to see it update.</p>
      <button onClick={() => setCount((c) => c + 1)}>Clicked {count} times</button>
    </main>
  );
}
